---
- name: Verify
  hosts: cert-manager-test-control-plane
  connection: docker
  gather_facts: false
  tasks:
    - name: Check executor dependencies
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present
      check_mode: true
      register: cert_manager_verify
      failed_when: cert_manager_verify.changed

    - name: Check ansible dependencies
      ansible.builtin.pip:
        name:
          - kubernetes
          - openshift
          - pyyaml
      check_mode: true
      register: cert_manager_verify
      failed_when: cert_manager_verify.changed

    - name: Check namespace
      kubernetes.core.k8s:
        name: "cert-manager"
        api_version: v1
        kind: Namespace
        state: present
      check_mode: true
      register: cert_manager_verify
      failed_when: cert_manager_verify.changed

    - name: Add jetstack chart repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"
      check_mode: true
      register: cert_manager_verify
      failed_when: cert_manager_verify.changed

    - name: Deploy latest version of cert-manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        update_repo_cache: true
        values:
          installCRDs: true
      check_mode: true
      register: cert_manager_verify
      failed_when: cert_manager_verify.changed
...
